/* eslint-disable @next/next/no-page-custom-font */
import './globals.css';
import { Inter } from '@next/font/google';

const inter = Inter({
  variable: '--inter-font',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
